### ISSUE TITLE
Useless malloc in ft_parser

### ISSUE THREAD

**Issue by BeBel42** [davidszkl/minishell#2]
tab = malloc(sizeof(char *) * (main->pipecount + 1));
is useless because you assign it to ft_split later
tab = ft_split(line, '|');

And it should be tab = malloc(sizeof(char *) * (main->pipecount + 2)); instead of + 1 anyway (for the null terminating pointer).

**Comment by BeBel42** [comment]
Same type of "+1 -> +2" issue:
	main->cline = malloc(sizeof(t_comm) * main->pipecount);
should be 
	main->cline = malloc(sizeof(t_comm) * (main->pipecount + 1));
because there are pipecount +1 commands, and if you want to NULL terminate the array:
	main->cline = malloc(sizeof(t_comm) * (main->pipecount + 2));

**Comment by davidszkl** [comment]
fixed
